//LOADING
export const SET_LOADING = 'SET_LOADING'

//LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

export const EXPIRED_TOKEN = 'EXPIRED_TOKEN'

//PRODUCTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const CHANGE_PRODUCT_QUANTITY_CART = 'CHANGE_PRODUCT_QUANTITY_CART'

export const SET_RELOAD_PRODUCTS = 'SET_RELOAD_PRODUCTS'