//LOGIN
export const LOGIN_REQUEST_ASYNC = 'LOGIN_REQUEST_ASYNC'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

//LOADING
export const LOADING = 'LOADING'