//LOADING
export const LOADING_START = 'LOADING_START'
export const LOADING_STOP = 'LOADING_STOP'

//LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'